service:
db:
  image: postgres
  volumes:
    - db-data:/var/lib/postgresql/data
  environment:
    - POSTGRES_DB=hotel_alura
    - POSTGRES_PASSWORD=
  expose:
    -5432
  restart: always

app:
  build: java
  ports:
    - 8080:8080
  environment:
    - POSTGRES_DB=hotel_alura
    - POSTGRES_HOST=db
    - POSTGRES_PASSWORD= 
  depends_on:
    - db
  restart: always
volumes:
  db-data: